name: Deploy ML Model

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 레포지토리 체크아웃
      uses: actions/checkout@v3

    - name: Docker 로그인
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


    - name: Docker 이미지 빌드 및 푸시
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ml-model:${{ github.sha }} .
        docker tag ${{ secrets.DOCKER_USERNAME }}/ml-model:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ml-model:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-model:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-model:latest

    - name: Kubernetes Rolling Update
      run: |
        kubectl set image deployment/ml-api ml-api=${{ secrets.DOCKER_USERNAME }}/ml-model:${{ github.sha }}
        kubectl rollout status deployment/ml-api
